export const TEMPLATE_NAMES: Record<string, string> = {
  scandinavian: "Modern Scandinavian",
  contemporary_grey: "Contemporary Grey",
  cozy_british: "Cozy British",
  luxury_penthouse: "Luxury Penthouse",
  minimalist_white: "Minimalist White",
  serene_bedroom: "Serene Bedroom",
  boutique_hotel: "Boutique Hotel",
  light_airy: "Light & Airy",
  modern_dining: "Modern Dining",
  rustic_farmhouse: "Rustic Farmhouse",
  modern_office: "Modern Home Office",
  creative_studio: "Creative Studio",
  white_background: "Pure White Background",
  grey_studio: "Grey Studio",
  showroom_floor: "Showroom Floor",
  custom: "Custom Prompt",
  virtual_patio: "Patio Terrace",
  virtual_garden: "English Garden",
  virtual_balcony: "City Balcony",
  virtual_hotel_lobby: "Hotel Lobby",
  virtual_restaurant: "Restaurant",
  virtual_cafe: "Cafe Interior",
  virtual_retail: "Retail Showroom",
  virtual_coastal: "Coastal Retreat",
  virtual_mid_century: "Mid-Century Modern",
  virtual_japandi: "Japandi",
  virtual_art_deco: "Art Deco",
  virtual_nursery: "Nursery",
  virtual_bathroom: "Bathroom",
};
